prevent-bots: false
# Enable if you want to keep a certain cooldown (500ms) between each message

receive-permission: "nmsg.receive"
# Players with this permission will receive the messages
# Leave blank to allow everyone

silent-permission: "nmsg.silent.force"
# Players with this permission will be silents

welcome: "&5Welcome &b%player% &5to our network!"
# Note: you can disable any message by clearing it

join-all: "&e[&a+&e] &b%player% &7(&b%to-server%&7)"
# Displayed to all players on BungeeCord (%player%, %to-server%)

join-to: "&e[&a+&e] &b%player%"
# Displayed to all players on the target server (%player%, %to-server%)

leave-all: "&e[&c-&e] &b%player% &7(&b%from-server%&7)"
# Displayed to all players on BungeeCord (%player%, %from-server%)

leave-from: "&e[&c-&e] &b%player%"
# Displayed to all players on the left server (%player%, %from-server%)

switch-all: "&e[&7>&e] &b%player% &7> &b%to-server%"
# Displayed to all players on BungeeCord (%player%, %from-server%, %to-server%)

switch-to: "&e[&7>&e] &b%player% &7< &b%from-server%"
# Displayed to all players on the target server (%player%, %from-server%, %to-server%)

switch-from: "&e[&7>&e] &b%player% &7> &b%to-server%"
# Displayed to all players on the left server (%player%, %from-server%, %to-server%)

servers: # Per-server configuration for [join-to, leave-from, switch-to, switch-from]
    factions:
        alias: "&2Factions&b"
        # Replaces the server name in [server, to-server, from-server] variables
        join-to: "&d%player% would like to fight!"
        leave-from: "&d%player% surrenders"
        switch-to: "&d%player% would like to fight!"
        switch-from: "&d%player% surrenders"
        # These message variants will only be sent to players on the server "factions"